### ISSUE TITLE
couldn't find a `pages` directory. Please create one under the project root

### ISSUE THREAD

**Issue by MohdevOfficiel** [craftzdog/craftzdog-homepage#6]
Error: > Couldn't find a `pages` directory. Please create one under the project root
    at Object.findPagesDir (C:\Users\USER HP\Development\ghost_homepage\node_modules\next\dist\lib\find-pages-dir.js:33:11)
    at new DevServer (C:\Users\USER HP\Development\ghost_homepage\node_modules\next\dist\server\dev\next-dev-server.js:110:44)
    at NextServer.createServer (C:\Users\USER HP\Development\ghost_homepage\node_modules\next\dist\server\next.js:102:20)
    at C:\Users\USER HP\Development\ghost_homepage\node_modules\next\dist\server\next.js:117:42
    at async NextServer.prepare (C:\Users\USER HP\Development\ghost_homepage\node_modules\next\dist\server\next.js:92:24)
    at async C:\Users\USER HP\Development\ghost_homepage\node_modules\next\dist\cli\next-dev.js:126:9

**Comment by Harry-Hopkinson** [comment]
I do not have this error

**Comment by Harry-Hopkinson** [comment]
create a pages folder

**Comment by MohdevOfficiel** [comment]
okey

**Comment by Harry-Hopkinson** [comment]
Does the error persist?

**Comment by MohdevOfficiel** [comment]
Not the error is fell, i dot make

Le dim. 23 janv. 2022 à 12:37, Harry Hopkinson ***@***.***> a
écrit :
